### ISSUE TITLE
XComMissions List includes incorrect alien units on NoTerrorOrBosses

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_AlienPack#14]
Line 40 of XComMissions.ini contains ChryssalidSoldier and hiveQueen in NoTerrorOrBosses. Remove this, and verify the rest of the file.

**Comment by TNychka** [comment]
For context: 
```
+InclusionExclusionLists=(ListID="NoTerrorOrBosses", \\
		bIncludeNames=true, \\
		TemplateName[0]="ChryssalidSoldier" \\
                TemplateName[1]="HiveQueen")
```
ListID is the type of mission
bIncludeNames is whether or not the listed units should appear. In this case the above code means that the ChryssalidSoldier and HiveQueen will appear on missions where there should be noTerrorOrBosses. This is not correct.

**Comment by fowlJ** [comment]
WotC stopped using InclusionLists entirely in favour of the new EncounterLists - I'm pretty sure that these can just be removed entirely, given that the EncounterLists file is set up already.

**Comment by TNychka** [comment]
In that case, the new task is to make sure that InclusionLists are no longer relevant and remove them.

**Comment by TNychka** [comment]
Fixed in clean up code PR, even if it is no longer relevant. The inclusionlists will be removed in a new issue.

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chrysallid soldiers and the hive queen spawn on missions where they should not spawn.](https://trello.com/c/sogdwbbO/5-chrysallid-soldiers-and-the-hive-queen-spawn-on-missions-where-they-should-not-spawn)
