### ISSUE TITLE
ADVENT Drones have no defined followers.

### ISSUE THREAD

**Issue by fowlJ** [X2LongWarOfTheChosen/LWOTC_AlienPack#18]
ADVENT Drones are configured in XComEncounterLists to appear as pod leaders, but have no allowed followers defined in their CharacterStats. This means that whenever they get chosen to appear as leaders instead of as followers, the game will fail to find any valid followers and so they will appear alone.

This is likely the cause for issue #17 as well, where a Drone leads a reinforcement pod but nothing else drops.

There are two ways to fix this - we can either add valid followers to the Drones' CharacterStats entry, which would let them lead properly, _or_ we could just remove them from the leader lists, which is how they were in the original alien pack.

**Comment by TNychka** [comment]
Right now we want to get this pack as close to the original as possible. Whoever takes this task should make sure that the current leaders/missions/ect. inis match up with the original configuration.

**Comment by fowlJ** [comment]
Got it - I'll take them out of the leader lists then.

**Comment by TNychka** [comment]
https://github.com/X2LongWarOfTheChosen/LWOTC_AlienPack/pull/20
