### ISSUE TITLE
Various Errors in XComEncounterLists.ini

### ISSUE THREAD

**Issue by fowlJ** [X2LongWarOfTheChosen/LWOTC_AlienPack#19]
- Drones appear in the 'NoHardCC' list, which is pretty much the opposite of where drones should appear.

- Chryssalid Soldiers and Chryssalid Hive Queens appear in 'TerrorFollowersNoChryssalid', which is not quite right for obvious reasons. 

- Lists for the 'Savage' SITREP add regular Chryssalids, which are already present in the vanilla list, rather than Chryssalid Soldiers.

- Mechs are added to DefaultLeaders twice, instead of being added to DefaultFollowers.

- Vanilla enemies are added to the lists in several places, which they should not be.

- Force level brackets are weird, with most enemies appearing through the early and midgame before disappearing entirely after around Force 16, meaning they are absent for probably the last 3-4 months of the campaign. Many enemies also appear much earlier than they do in the LWAP. Numbers should be revised to be about the same as the ones listed in the CharacterStats file.

**Comment by TNychka** [comment]
https://github.com/X2LongWarOfTheChosen/LWOTC_AlienPack/pull/20
