### ISSUE TITLE
Add reveal animation to drones

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_AlienPack#21]
Robojumper has given us permission to use the drone animation from their mod here https://steamcommunity.com/sharedfiles/filedetails/?id=871340811. Add this to the drones for reveals.

**Comment by RevZero** [comment]
I will give this a try. Looks like a good exercise to get started.

**Comment by TNychka** [comment]
It's yours

**Comment by TNychka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add reveal animation to drones #21](https://trello.com/c/EzqfzNmm/4-add-reveal-animation-to-drones-21)

**Comment by RevZero** [comment]
See follow ups.

**Comment by RevZero** [comment]
See follow up issues.
