### ISSUE TITLE
Crashes from incorrectly setup tactical transient classes

### ISSUE THREAD

**Issue by Favid** [X2LongWarOfTheChosen/LWOTC_AlienPack#31]
**Describe the bug**
In the base game, tactical transient game state classes were defined by adding their names to the TransientTacticalClassNames list in XComGame.ini. In WotC, those classes must have their bTacticalTransient flag set to true. Because this has not been done, the game is crashing.

**To Reproduce**
1. Start a mission where at least one enemy from the Alien Pack is present who has Traverse Fire (AdvGunnerM3), Lightning Reflexes (ChryssalidSoldier), or Locked On (AdvGunnerM2, AdvGunnerM3).
2. Complete mission.
3. Start a new mission. The game will crash at the loading screen.

**Comment by TNychka** [comment]
Fixed in #33
