### ISSUE TITLE
Improve compatibility with other mods that override X2Action_MoveClimbWall

### ISSUE THREAD

**Issue by Favid** [X2LongWarOfTheChosen/LWOTC_AlienPack#32]
X2Action_MoveClimbWall is a popular class to override for mods that add new enemies. As such, this mod should conform to the standard set by other mods so that it will be compatible with those mods.

To test if this is working properly, loading this mod along with World War L should not cause any slowdown on the Geoscape.

Convo with robojumper describing how to do this:

> Favid:
I noticed that both ABA and WWL override X2Action_MoveClimbWall, and using both of them won't cause the world map slowdown. But if my own mod does that override and I'm running WWL, I get the slowdown. How did you achieve this?

> robojumper:
We rely on a quirk of the INI merger
Identical lines with a + prefix are only added once (contrary to the . prefix)
So you need to copy the exact same line
That's also why the overriding class is in a package separate from the main mod(s)

So we need to:
1. Rename X2Action_MoveClimbWall_LW to X2Action_MoveClimbWall_Override
2. Move this class into a new package named WallClimbOverride
3. Make sure that the override line in XComEngine.ini looks exactly like this:

> +ModClassOverrides=(BaseGameClass="X2Action_MoveClimbWall", ModClass="WallClimbOverride.X2Action_MoveClimbWall_Override")

**Comment by TNychka** [comment]
Fixed in #34
